
spring:
  datasource:
    url: jdbc:h2:mem:realdb
    username: test
    password:
  jpa:

    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enable: true