spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: MySql8.0.36
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false


---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    passeord: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled : true
